[env:bootloader]
platform = ststm32
board = disco_g071rb
framework = stm32cube
board_build.mcu = stm32g071rbt6
board_build.f_cpu = 16000000L
upload_protocol = stlink
board_build.ldscript = STM32G070KBTX_BOOT.ld
build_flags =
    -Iinclude
    -DSTM32G071xx
    -DUSE_HAL_DRIVER
